spring:
  datasource:
    url: jdbc:hsqldb:mem:batchdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver
    platform: hsqldb
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
